const yelpUser = [
    {
        user_id: "l6BmjZMeQD3rDxWUbiAiow",
        name: "Rashmi",
        review_count: 95,
        yelping_since: "2013-10-08 23:11:33",
        useful: 84,
        funny: 17,
        cool: 25,
        elite: "2015,2016,2017",
        fans: 5,
        average_stars: 4.03,
        compliment_hot: 2,
        compliment_more: 0,
        compliment_profile: 0,
        compliment_cute: 0,
        compliment_list: 0,
        compliment_note: 1,
        compliment_plain: 1,
        compliment_cool: 1,
        compliment_funny: 1,
        compliment_writer: 2,
        compliment_photos: 0
    },
    {
        user_id: "Ocha4kZBHb4JK0lOWvE0sg",
        name: "Jenna",
        review_count: 33,
        yelping_since: "2013-02-21 22:29:06",
        useful: 48,
        funny: 22,
        cool: 16,
        elite: "",
        compliment_hot: 1,
        compliment_more: 0,
        compliment_profile: 0,
        compliment_cute: 0,
        compliment_list: 0,
        compliment_note: 0,
        compliment_plain: 0,
        compliment_cool: 1,
        compliment_funny: 1,
        compliment_writer: 0,
        compliment_photos: 0
    },
    {
        user_id: "bc8C_eETBWL0olvFSJJd0w",
        name: "David",
        review_count: 16,
        yelping_since: "2013-10-04 00:16:10",
        useful: 28,
        funny: 8,
        cool: 10,
        elite: "",
        fans: 0,
        average_stars: 3.71,
        compliment_hot: 0,
        compliment_more: 0,
        compliment_profile: 0,
        compliment_cute: 0,
        compliment_list: 0,
        compliment_note: 1,
        compliment_plain: 0,
        compliment_cool: 0,
        compliment_funny: 0,
        compliment_writer: 0,
        compliment_photos: 0
    },
    {
        user_id: "dD0gZpBctWGdWo9WlGuhlA",
        name: "Angela",
        review_count: 17,
        yelping_since: "2014-05-22 15:57:30",
        useful: 30,
        funny: 4,
        cool: 14,
        elite: "",
        fans: 5,
        average_stars: 4.85,
        compliment_hot: 1,
        compliment_more: 0,
        compliment_profile: 0,
        compliment_cute: 0,
        compliment_list: 0,
        compliment_note: 0,
        compliment_plain: 2,
        compliment_cool: 0,
        compliment_funny: 0,
        compliment_writer: 1,
        compliment_photos: 0
    },
    {
        user_id: "MM4RJAeH6yuaN8oZDSt0RA",
        name: "Nancy",
        review_count: 361,
        yelping_since: "2013-10-23 07:02:50",
        useful: 1114,
        funny: 279,
        cool: 665,
        elite: "2015,2016,2017,2018",
        fans: 39,
        average_stars: 4.08,
        compliment_hot: 28,
        compliment_more: 1,
        compliment_profile: 0,
        compliment_cute: 0,
        compliment_list: 1,
        compliment_note: 16,
        compliment_plain: 57,
        compliment_cool: 80,
        compliment_funny: 80,
        compliment_writer: 25,
        compliment_photos: 5
    },
    {
        user_id: "jRyO2V1pA4CdVVqCIOPc1Q",
        name: "Marilyn",
        review_count: 214,
        yelping_since: "2011-06-23 08:05:13",
        useful: 3475,
        funny: 2424,
        cool: 3048,
        elite: "2015,2016,2017,2018",
        fans: 186,
        average_stars: 4.2,
        compliment_hot: 350,
        compliment_more: 46,
        compliment_profile: 50,
        compliment_cute: 44,
        compliment_list: 3,
        compliment_note: 221,
        compliment_plain: 404,
        compliment_cool: 483,
        compliment_funny: 483,
        compliment_writer: 149,
        compliment_photos: 195
    },
    {
        user_id: "TEtzbpgA2BFBrC0y0sCbfw",
        name: "Keane",
        review_count: 1122,
        yelping_since: "2006-02-15 18:29:35",
        useful: 13311,
        funny: 19356,
        cool: 15319,
        elite: "2006,2007,2008,2009,2010,2011,2012,2013",
        fans: 696,
        average_stars: 4.39,
        compliment_hot: 5233,
        compliment_more: 314,
        compliment_profile: 333,
        compliment_cute: 889,
        compliment_list: 152,
        compliment_note: 1600,
        compliment_plain: 3635,
        compliment_cool: 4991,
        compliment_funny: 4991,
        compliment_writer: 1086,
        compliment_photos: 428
    },
    {
        user_id: "KGuqerdeNhxzXZEyBaqqSw",
        name: "Andre",
        review_count: 6,
        yelping_since: "2014-06-07 01:50:09",
        useful: 1,
        funny: 0,
        cool: 1,
        elite: "",
        fans: 0,
        average_stars: 4.33,
        compliment_hot: 0,
        compliment_more: 0,
        compliment_profile: 0,
        compliment_cute: 0,
        compliment_list: 0,
        compliment_note: 0,
        compliment_plain: 0,
        compliment_cool: 0,
        compliment_funny: 0,
        compliment_writer: 0,
        compliment_photos: 0
    },
    {
        user_id: "T0gWkTHWRChVUe_Dn1F8nw",
        name: "Tanya",
        review_count: 859,
        yelping_since: "2005-07-20 22:38:17",
        useful: 1630,
        funny: 693,
        cool: 1244,
        elite: "2006,2007,2008,2009,2010,2011,2012",
        fans: 57,
        average_stars: 4.21,
        compliment_hot: 60,
        compliment_more: 16,
        compliment_profile: 7,
        compliment_cute: 7,
        compliment_list: 3,
        compliment_note: 31,
        compliment_plain: 72,
        compliment_cool: 95,
        compliment_funny: 95,
        compliment_writer: 34,
        compliment_photos: 2
    },
    {
        user_id: "FuTJWFYm4UKqewaosss1KA",
        name: "Trace",
        review_count: 124,
        yelping_since: "2008-12-10 22:59:45",
        useful: 202,
        funny: 70,
        cool: 185,
        elite: "",
        fans: 15,
        average_stars: 4.53,
        compliment_hot: 13,
        compliment_more: 3,
        compliment_profile: 0,
        compliment_cute: 2,
        compliment_list: 0,
        compliment_note: 12,
        compliment_plain: 8,
        compliment_cool: 14,
        compliment_funny: 14,
        compliment_writer: 3,
        compliment_photos: 5
    },
    {
        user_id: "LUlKtaM3nXd",
        name: "Peter",
        review_count: 47,
        yelping_since: "2014-01-05 20:45:54",
        useful: 57,
        funny: 26,
        cool: 34,
        elite: "2017,2018",
        fans: 9,
        average_stars: 3.6,
        compliment_hot: 1,
        compliment_more: 0,
        compliment_profile: 0,
        compliment_cute: 0,
        compliment_list: 0,
        compliment_note: 4,
        compliment_plain: 11,
        compliment_cool: 5,
        compliment_funny: 5,
        compliment_writer: 4,
        compliment_photos: 3
    },
    {
        user_id: "_DaFdmq0gtXf1spn1qC_1Q",
        name: "Edie",
        review_count: 77,
        yelping_since: "2009-10-26 01:00:40",
        useful: 71,
        funny: 16,
        cool: 22,
        elite: "",
        fans: 3,
        average_stars: 3.48,
        compliment_hot: 0,
        compliment_more: 1,
        compliment_profile: 0,
        compliment_cute: 0,
        compliment_list: 0,
        compliment_note: 2,
        compliment_plain: 2,
        compliment_cool: 1,
        compliment_funny: 1,
        compliment_writer: 0,
        compliment_photos: 0
    },
    {
        user_id: "iAd8XaHxv05iXyEiZ62Ibw",
        name: "Gabriella",
        review_count: 11,
        yelping_since: "2012-11-13 00:23:51",
        useful: 12,
        funny: 4,
        cool: 3,
        elite: "",
        fans: 2,
        average_stars: 3.5,
        compliment_hot: 0,
        compliment_more: 0,
        compliment_profile: 0,
        compliment_cute: 0,
        compliment_list: 0,
        compliment_note: 0,
        compliment_plain: 1,
        compliment_cool: 0,
        compliment_funny: 0,
        compliment_writer: 1,
        compliment_photos: 0
    },
    {
        user_id: "w8p4JW6-ERsbg8aB5wjEAg",
        name: "Emily",
        review_count: 22,
        yelping_since: "2010-01-23 04:55:04",
        useful: 31,
        funny: 17,
        cool: 12,
        elite: "",
        fans: 0,
        average_stars: 3.95,
        compliment_hot: 0,
        compliment_more: 1,
        compliment_profile: 0,
        compliment_cute: 0,
        compliment_list: 0,
        compliment_note: 2,
        compliment_plain: 1,
        compliment_cool: 4,
        compliment_funny: 4,
        compliment_writer: 1,
        compliment_photos: 1
    },
    {
        user_id: "fktnDzpjYBUG5a-w_xq01A",
        name: "Victoria",
        review_count: 143,
        yelping_since: "2009-04-09 01:05:03",
        useful: 483,
        funny: 285,
        cool: 342,
        elite: "",
        fans: 42,
        average_stars: 3.9,
        compliment_hot: 45,
        compliment_more: 7,
        compliment_profile: 4,
        compliment_cute: 11,
        compliment_list: 0,
        compliment_note: 25,
        compliment_plain: 29,
        compliment_cool: 49,
        compliment_funny: 49,
        compliment_writer: 13,
        compliment_photos: 29
    },
    {
        user_id: "iPJAN6rJHv92WE2h9b3lAA",
        name: "Richard",
        review_count: 9,
        yelping_since: "2013-09-30 23:58:16",
        useful: 11,
        funny: 6,
        cool: 5,
        elite: "",
        fans: 1,
        average_stars: 4.5,
        compliment_hot: 3,
        compliment_more: 0,
        compliment_profile: 0,
        compliment_cute: 0,
        compliment_list: 0,
        compliment_note: 0,
        compliment_plain: 1,
        compliment_cool: 0,
        compliment_funny: 0,
        compliment_writer: 0,
        compliment_photos: 1
    },
    {
        user_id: "AWCY8laHjH0-3HMT0LGpUA",
        name: "Jin",
        review_count: 732,
        yelping_since: "2010-07-09 15:53:01",
        useful: 1104,
        funny: 417,
        cool: 586,
        elite: "2011,2012,2013,2014,2015,2016",
        fans: 71,
        average_stars: 3.79,
        compliment_hot: 89,
        compliment_more: 8,
        compliment_profile: 11,
        compliment_cute: 18,
        compliment_list: 8,
        compliment_note: 83,
        compliment_plain: 196,
        compliment_cool: 185,
        compliment_funny: 185,
        compliment_writer: 56,
        compliment_photos: 42
    },
    {
        user_id: "CXi7I5J-ItLGJNyKPkI5gA",
        name: "Cyndi",
        review_count: 57,
        yelping_since: "2011-06-27 05:24:10",
        useful: 72,
        funny: 22,
        cool: 34,
        elite: "",
        fans: 4,
        average_stars: 4.1,
        compliment_hot: 2,
        compliment_more: 1,
        compliment_profile: 0,
        compliment_cute: 0,
        compliment_list: 0,
        compliment_note: 2,
        compliment_plain: 1,
        compliment_cool: 1,
        compliment_funny: 1,
        compliment_writer: 2,
        compliment_photos: 1
    },
    {
        user_id: "3TJcP0stfxjWGsLuGQgQdg",
        name: "Diana",
        review_count: 453,
        yelping_since: "2012-09-14 21:40:12",
        useful: 3578,
        funny: 1501,
        cool: 2532,
        elite: "2014,2015,2016,2017,2018",
        fans: 124,
        average_stars: 3.58,
        compliment_hot: 151,
        compliment_more: 12,
        compliment_profile: 13,
        compliment_cute: 13,
        compliment_list: 1,
        compliment_note: 78,
        compliment_plain: 188,
        compliment_cool: 246,
        compliment_funny: 246,
        compliment_writer: 101,
        compliment_photos: 44
    },
    {
        user_id: "hQ98T_hy1CoSWw55zA49VQ",
        name: "Jamey",
        review_count: 44,
        yelping_since: "2015-11-02 23:41:13",
        useful: 16,
        funny: 3,
        cool: 2,
        elite: "",
        fans: 0,
        average_stars: 3.1,
        compliment_hot: 0,
        compliment_more: 0,
        compliment_profile: 0,
        compliment_cute: 0,
        compliment_list: 0,
        compliment_note: 0,
        compliment_plain: 0,
        compliment_cool: 0,
        compliment_funny: 0,
        compliment_writer: 0,
        compliment_photos: 0
    },
    {
        user_id: "zzpgpo54-_P-4rzzBtOuLQ",
        name: "Aurélie",
        review_count: 1563,
        yelping_since: "2013-10-23 09:21:57",
        useful: 4172,
        funny: 1661,
        cool: 3246,
        elite: "2013,2014,2016,2017,2018",
        fans: 99,
        average_stars: 3.89,
        compliment_hot: 628,
        compliment_more: 9,
        compliment_profile: 16,
        compliment_cute: 29,
        compliment_list: 8,
        compliment_note: 354,
        compliment_plain: 776,
        compliment_cool: 559,
        compliment_funny: 559,
        compliment_writer: 75,
        compliment_photos: 119
    },
    {
        user_id: "pU6GoRTcl1rIOi6zMynjog",
        name: "Javier",
        review_count: 470,
        yelping_since: "2011-12-16 16:13:01",
        useful: 1655,
        funny: 1007,
        cool: 974,
        elite: "2015,2016,2017,2018",
        fans: 71,
        average_stars: 3.45,
        compliment_hot: 16,
        compliment_more: 8,
        compliment_profile: 1,
        compliment_cute: 0,
        compliment_list: 0,
        compliment_note: 42,
        compliment_plain: 32,
        compliment_cool: 64,
        compliment_funny: 64,
        compliment_writer: 35,
        compliment_photos: 10
    },
    {
        user_id: "oIHhfloe5VQamDFDB2dr1Q",
        name: "Lea",
        review_count: 127,
        yelping_since: "2010-01-29 02:39:45",
        useful: 193,
        funny: 52,
        cool: 53,
        elite: "",
        fans: 5,
        average_stars: 4.05,
        compliment_hot: 2,
        compliment_more: 1,
        compliment_profile: 0,
        compliment_cute: 1,
        compliment_list: 0,
        compliment_note: 0,
        compliment_plain: 6,
        compliment_cool: 1,
        compliment_funny: 1,
        compliment_writer: 1,
        compliment_photos: 3
    },
    {
        user_id: "_ICqwy7SW8J6OJBab1HkwA",
        name: "allison",
        review_count: 391,
        yelping_since: "2007-10-06 02:42:28",
        useful: 708,
        funny: 316,
        cool: 399,
        elite: "2008,2009",
        fans: 13,
        average_stars: 4.31,
        compliment_hot: 10,
        compliment_more: 6,
        compliment_profile: 3,
        compliment_cute: 5,
        compliment_list: 4,
        compliment_note: 21,
        compliment_plain: 39,
        compliment_cool: 23,
        compliment_funny: 23,
        compliment_writer: 8,
        compliment_photos: 1
    },
    {
        user_id: "J9HamWsxKorlPGUAXy-M9Q",
        name: "Ronald",
        review_count: 336,
        yelping_since: "2010-05-17 22:59:40",
        useful: 431,
        funny: 189,
        cool: 228,
        elite: "2012,2013,2014,2015,2016,2017",
        fans: 19,
        average_stars: 3.81,
        compliment_hot: 11,
        compliment_more: 2,
        compliment_profile: 3,
        compliment_cute: 0,
        compliment_list: 0,
        compliment_note: 12,
        compliment_plain: 15,
        compliment_cool: 19,
        compliment_funny: 19,
        compliment_writer: 8,
        compliment_photos: 4
    },
    {
        user_id: "t8Whyn2ZWS34TxHsr2mpbg",
        name: "Erica",
        review_count: 48,
        yelping_since: "2007-10-05 16:05:28",
        useful: 108,
        funny: 39,
        cool: 33,
        elite: "",
        fans: 7,
        average_stars: 3.57,
        compliment_hot: 14,
        compliment_more: 4,
        compliment_profile: 1,
        compliment_cute: 2,
        compliment_list: 0,
        compliment_note: 1,
        compliment_plain: 10,
        compliment_cool: 13,
        compliment_funny: 13,
        compliment_writer: 12,
        compliment_photos: 2
    },
    {
        user_id: "nRagjGVuSALgQ4KfGLn8Ig",
        name: "Christene",
        review_count: 9,
        yelping_since: "2013-05-14 20:57:57",
        useful: 5,
        funny: 0,
        cool: 3,
        elite: "",
        fans: 0,
        average_stars: 4.44,
        compliment_hot: 0,
        compliment_more: 0,
        compliment_profile: 0,
        compliment_cute: 0,
        compliment_list: 0,
        compliment_note: 0,
        compliment_plain: 0,
        compliment_cool: 0,
        compliment_funny: 0,
        compliment_writer: 0,
        compliment_photos: 0
    },
    {
        user_id: "djQLJTLA4Tx7TpzYCKIqJQ",
        name: "Kris",
        review_count: 167,
        yelping_since: "2011-08-10 22:57:03",
        useful: 423,
        funny: 212,
        cool: 213,
        elite: "2016,2017",
        fans: 9,
        average_stars: 4.16,
        compliment_hot: 11,
        compliment_more: 1,
        compliment_profile: 1,
        compliment_cute: 0,
        compliment_list: 0,
        compliment_note: 13,
        compliment_plain: 25,
        compliment_cool: 7,
        compliment_funny: 7,
        compliment_writer: 12,
        compliment_photos: 1
    },
    {
        user_id: "xxhjX14h8cQyKSuTQFy1Lg",
        name: "Sharon",
        review_count: 443,
        yelping_since: "2011-03-12 02:30:38",
        useful: 907,
        funny: 532,
        cool: 573,
        elite: "",
        fans: 13,
        average_stars: 3.59,
        compliment_hot: 16,
        compliment_more: 2,
        compliment_profile: 1,
        compliment_cute: 3,
        compliment_list: 0,
        compliment_note: 24,
        compliment_plain: 33,
        compliment_cool: 57,
        compliment_funny: 57,
        compliment_writer: 18,
        compliment_photos: 8
    },
    {
        user_id: "NEN5RFpZp7DE6K1PK2KZzg",
        name: "Amber",
        review_count: 4,
        yelping_since: "2014-08-23 03:49:18",
        useful: 10,
        funny: 1,
        cool: 3,
        elite: "",
        fans: 1,
        average_stars: 2.0,
        compliment_hot: 0,
        compliment_more: 0,
        compliment_profile: 0,
        compliment_cute: 0,
        compliment_list: 0,
        compliment_note: 0,
        compliment_plain: 0,
        compliment_cool: 0,
        compliment_funny: 0,
        compliment_writer: 0,
        compliment_photos: 0
    },
    {
        user_id: "Fzz-0v1yHLaWuTV64b1miA",
        name: "A",
        review_count: 19,
        yelping_since: "2013-05-28 17:49:42",
        useful: 33,
        funny: 4,
        cool: 3,
        elite: "",
        fans: 1,
        average_stars: 2.64,
        compliment_hot: 0,
        compliment_more: 0,
        compliment_profile: 0,
        compliment_cute: 0,
        compliment_list: 0,
        compliment_note: 0,
        compliment_plain: 1,
        compliment_cool: 0,
        compliment_funny: 0,
        compliment_writer: 0,
        compliment_photos: 0
    },
    {
        user_id: "CbmNBkKa9QKNxPiN_whFUw",
        name: "Desiree",
        review_count: 108,
        yelping_since: "2016-01-14 09:00:28",
        useful: 88,
        funny: 9,
        cool: 32,
        elite: "2018",
        fans: 2,
        average_stars: 4.25,
        compliment_hot: 1,
        compliment_more: 1,
        compliment_profile: 1,
        compliment_cute: 0,
        compliment_list: 0,
        compliment_note: 0,
        compliment_plain: 1,
        compliment_cool: 0,
        compliment_funny: 0,
        compliment_writer: 0,
        compliment_photos: 0
    },
    {
        user_id: "3KkT6SmPFLGvBS1pnDBr8g",
        name: "Katharine",
        review_count: 412,
        yelping_since: "2008-06-13 14:48:51",
        useful: 1816,
        funny: 463,
        cool: 1341,
        elite: "2011,2012,2013,2014,2015,2016,2017,2018",
        fans: 77,
        average_stars: 4.02,
        compliment_hot: 106,
        compliment_more: 3,
        compliment_profile: 4,
        compliment_cute: 1,
        compliment_list: 1,
        compliment_note: 60,
        compliment_plain: 64,
        compliment_cool: 140,
        compliment_funny: 140,
        compliment_writer: 120,
        compliment_photos: 65
    },
    {
        user_id: "3gniF5P3L_WcoR8zx7wXxA",
        name: "Jamison",
        review_count: 4,
        yelping_since: "2017-03-13 19:50:46",
        useful: 2,
        funny: 0,
        cool: 0,
        elite: "",
        fans: 0,
        average_stars: 4.2,
        compliment_hot: 0,
        compliment_more: 0,
        compliment_profile: 0,
        compliment_cute: 0,
        compliment_list: 0,
        compliment_note: 0,
        compliment_plain: 0,
        compliment_cool: 0,
        compliment_funny: 0,
        compliment_writer: 0,
        compliment_photos: 0
    },
    {
        user_id: "ICwMfseYkrB0ZEK8tDUOHw",
        name: "Annie",
        review_count: 914,
        yelping_since: "2009-01-07 22:24:30",
        useful: 5227,
        funny: 2674,
        cool: 2890,
        elite: "2010,2011,2012",
        fans: 407,
        average_stars: 4.06,
        compliment_hot: 382,
        compliment_more: 57,
        compliment_profile: 42,
        compliment_cute: 86,
        compliment_list: 47,
        compliment_note: 856,
        compliment_plain: 3260,
        compliment_cool: 891,
        compliment_funny: 891,
        compliment_writer: 284,
        compliment_photos: 143
    },
    {
        user_id: "eSlOI3GhroEtcbaD_nFXJQ",
        name: "Jason",
        review_count: 2518,
        yelping_since: "2011-05-28 21:42:38",
        useful: 16349,
        funny: 8340,
        cool: 13924,
        elite: "2012,2013,2014,2015,2016,2017,2018",
        fans: 251,
        average_stars: 3.61,
        compliment_hot: 711,
        compliment_more: 84,
        compliment_profile: 59,
        compliment_cute: 18,
        compliment_list: 16,
        compliment_note: 361,
        compliment_plain: 2861,
        compliment_cool: 2267,
        compliment_funny: 2267,
        compliment_writer: 274,
        compliment_photos: 218
    },
    {
        user_id: "kMcz3zQgNjZYV65qY9ztGA",
        name: "Sara",
        review_count: 207,
        yelping_since: "2012-12-10 04:55:46",
        useful: 289,
        funny: 72,
        cool: 133,
        elite: "2013,2014,2015,2016,2017,2018",
        fans: 33,
        average_stars: 3.82,
        compliment_hot: 13,
        compliment_more: 6,
        compliment_profile: 2,
        compliment_cute: 2,
        compliment_list: 0,
        compliment_note: 27,
        compliment_plain: 29,
        compliment_cool: 16,
        compliment_funny: 16,
        compliment_writer: 11,
        compliment_photos: 11
    },
    {
        user_id: "QiDtS54JwTGeH81c-a84WQ",
        name: "Maria",
        review_count: 100,
        yelping_since: "2010-01-26 15:36:03",
        useful: 363,
        funny: 90,
        cool: 203,
        elite: "2011,2012,2013",
        fans: 21,
        average_stars: 4.39,
        compliment_hot: 33,
        compliment_more: 6,
        compliment_profile: 2,
        compliment_cute: 6,
        compliment_list: 0,
        compliment_note: 36,
        compliment_plain: 61,
        compliment_cool: 75,
        compliment_funny: 75,
        compliment_writer: 19,
        compliment_photos: 18
    },
    {
        user_id: "rnU1EFMSnVJGrQxrnjaODg",
        name: "Fred",
        review_count: 431,
        yelping_since: "2010-12-28 01:37:20",
        useful: 3157,
        funny: 1338,
        cool: 2158,
        elite: "2014,2015,2016,2017,2018",
        fans: 58,
        average_stars: 3.95,
        compliment_hot: 146,
        compliment_more: 22,
        compliment_profile: 3,
        compliment_cute: 1,
        compliment_list: 0,
        compliment_note: 163,
        compliment_plain: 118,
        compliment_cool: 201,
        compliment_funny: 201,
        compliment_writer: 58,
        compliment_photos: 112
    },
    {
        user_id: "JnHaPHkRO2_8V-DysmIBVw",
        name: "Christopher",
        review_count: 318,
        yelping_since: "2015-01-17 17:04:09",
        useful: 400,
        funny: 175,
        cool: 223,
        elite: "2016,2017,2018",
        fans: 24,
        average_stars: 3.64,
        compliment_hot: 9,
        compliment_more: 4,
        compliment_profile: 1,
        compliment_cute: 0,
        compliment_list: 0,
        compliment_note: 2,
        compliment_plain: 4,
        compliment_cool: 4,
        compliment_funny: 4,
        compliment_writer: 2,
        compliment_photos: 5
    },
    {
        user_id: "EZbvMdvCA2D9vF6VjILYXA",
        name: "Christy",
        review_count: 1,
        yelping_since: "2015-12-29 20:26:10",
        useful: 0,
        funny: 0,
        cool: 0,
        elite: "",
        fans: 0,
        average_stars: 5.0,
        compliment_hot: 0,
        compliment_more: 0,
        compliment_profile: 0,
        compliment_cute: 0,
        compliment_list: 0,
        compliment_note: 0,
        compliment_plain: 0,
        compliment_cool: 0,
        compliment_funny: 0,
        compliment_writer: 0,
        compliment_photos: 0
    },
    {
        user_id: "pDAqvfflIM4AM23VRpqAaw",
        name: "Jenna",
        review_count: 17,
        yelping_since: "2012-07-28 01:19:04",
        useful: 64,
        funny: 6,
        cool: 50,
        elite: "",
        fans: 3,
        average_stars: 4.95,
        compliment_hot: 2,
        compliment_more: 0,
        compliment_profile: 0,
        compliment_cute: 0,
        compliment_list: 0,
        compliment_note: 1,
        compliment_plain: 4,
        compliment_cool: 0,
        compliment_funny: 0,
        compliment_writer: 0,
        compliment_photos: 0
    },
    {
        user_id: "gGlFgp4nXNL5azpUtLK05w",
        name: "Lindsay",
        review_count: 87,
        yelping_since: "2008-04-12 14:29:44",
        useful: 240,
        funny: 78,
        cool: 101,
        elite: "2010,2011,2012,2013,2014",
        fans: 4,
        average_stars: 3.24,
        compliment_hot: 20,
        compliment_more: 6,
        compliment_profile: 2,
        compliment_cute: 0,
        compliment_list: 0,
        compliment_note: 17,
        compliment_plain: 9,
        compliment_cool: 22,
        compliment_funny: 22,
        compliment_writer: 12,
        compliment_photos: 1
    },
    {
        user_id: "NcUMNz6tAahD6mDmuKwYIA",
        name: "Karen",
        review_count: 85,
        yelping_since: "2008-07-13 17:51:38",
        useful: 63,
        funny: 25,
        cool: 45,
        elite: "2017,2018",
        fans: 4,
        average_stars: 4.4,
        compliment_hot: 1,
        compliment_more: 0,
        compliment_profile: 0,
        compliment_cute: 0,
        compliment_list: 0,
        compliment_note: 1,
        compliment_plain: 3,
        compliment_cool: 1,
        compliment_funny: 1,
        compliment_writer: 3,
        compliment_photos: 0
    },
    {
        user_id: "gvKlBHFA6VXb9AksWcPMjw",
        name: "Kenny",
        review_count: 130,
        yelping_since: "2009-09-25 17:13:17",
        useful: 137,
        funny: 62,
        cool: 69,
        elite: "",
        fans: 20,
        average_stars: 3.95,
        compliment_hot: 1,
        compliment_more: 0,
        compliment_profile: 0,
        compliment_cute: 0,
        compliment_list: 0,
        compliment_note: 5,
        compliment_plain: 8,
        compliment_cool: 3,
        compliment_funny: 3,
        compliment_writer: 2,
        compliment_photos: 1
    },
    {
        user_id: "WnwpWcNcJhHi39gdIUfJuQ",
        name: "Larry",
        review_count: 81,
        yelping_since: "2010-07-05 17:03:04",
        useful: 336,
        funny: 131,
        cool: 160,
        elite: "",
        fans: 8,
        average_stars: 3.21,
        compliment_hot: 3,
        compliment_more: 1,
        compliment_profile: 0,
        compliment_cute: 0,
        compliment_list: 0,
        compliment_note: 10,
        compliment_plain: 15,
        compliment_cool: 15,
        compliment_funny: 15,
        compliment_writer: 4,
        compliment_photos: 4
    },
    {
        user_id: "HmILc-lgVKZS7mWNdYCSJw",
        name: "Adrianna",
        review_count: 231,
        yelping_since: "2011-03-19 01:40:12",
        useful: 475,
        funny: 190,
        cool: 187,
        elite: "2014,2015,2016",
        fans: 31,
        average_stars: 3.6,
        compliment_hot: 38,
        compliment_more: 4,
        compliment_profile: 6,
        compliment_cute: 1,
        compliment_list: 0,
        compliment_note: 13,
        compliment_plain: 15,
        compliment_cool: 6,
        compliment_funny: 6,
        compliment_writer: 4,
        compliment_photos: 5
    },
    {
        user_id: "lesnCKZUYH554j-EDZBlTw",
        name: "Morgan",
        review_count: 6,
        yelping_since: "2015-07-27 20:10:53",
        useful: 2,
        funny: 0,
        cool: 1,
        elite: "",
        fans: 0,
        average_stars: 2.43,
        compliment_hot: 0,
        compliment_more: 0,
        compliment_profile: 0,
        compliment_cute: 0,
        compliment_list: 0,
        compliment_note: 1,
        compliment_plain: 0,
        compliment_cool: 0,
        compliment_funny: 0,
        compliment_writer: 0,
        compliment_photos: 0
    },
    {
        user_id: "alUuOskFSl1bODjnce2PpQ",
        name: "Regina",
        review_count: 1053,
        yelping_since: "2008-12-05 07:16:22",
        useful: 11769,
        funny: 6997,
        cool: 9594,
        elite: "2013,2014,2015,2016,2017,2018",
        fans: 231,
        average_stars: 3.66,
        compliment_hot: 480,
        compliment_more: 46,
        compliment_profile: 29,
        compliment_cute: 9,
        compliment_list: 5,
        compliment_note: 419,
        compliment_plain: 611,
        compliment_cool: 822,
        compliment_funny: 822,
        compliment_writer: 475,
        compliment_photos: 338
    },
    {
        user_id: "hf27xTME3EiCp6NL6VtWZQ",
        name: "Kristine",
        review_count: 108,
        yelping_since: "2010-08-28 09:14:34",
        useful: 391,
        funny: 344,
        cool: 340,
        elite: "",
        fans: 8,
        average_stars: 3.91,
        compliment_hot: 4,
        compliment_more: 5,
        compliment_profile: 2,
        compliment_cute: 2,
        compliment_list: 0,
        compliment_note: 1,
        compliment_plain: 1,
        compliment_cool: 8,
        compliment_funny: 8,
        compliment_writer: 4,
        compliment_photos: 2
    },
    {
        user_id: "1a36KbE7XH31Uo4fkmdkqQ",
        name: "Noah",
        review_count: 26,
        yelping_since: "2012-12-01 03:40:27",
        useful: 17,
        funny: 3,
        cool: 9,
        elite: "",
        fans: 1,
        average_stars: 4.57,
        compliment_hot: 0,
        compliment_more: 0,
        compliment_profile: 0,
        compliment_cute: 0,
        compliment_list: 0,
        compliment_note: 1,
        compliment_plain: 0,
        compliment_cool: 1,
        compliment_funny: 1,
        compliment_writer: 1,
        compliment_photos: 2
    },
    {
        user_id: "tAgzrWAxZivvK8-KqPzNCg",
        name: "Faisal",
        review_count: 13,
        yelping_since: "2011-03-17 23:35:32",
        useful: 10,
        funny: 1,
        cool: 5,
        elite: "",
        fans: 0,
        average_stars: 3.54,
        compliment_hot: 0,
        compliment_more: 1,
        compliment_profile: 0,
        compliment_cute: 0,
        compliment_list: 0,
        compliment_note: 0,
        compliment_plain: 0,
        compliment_cool: 0,
        compliment_funny: 0,
        compliment_writer: 0,
        compliment_photos: 0
    },
    {
        user_id: "TYCkjEHPSJSnFb6m6GDluw",
        name: "Corrina",
        review_count: 381,
        yelping_since: "2008-10-06 16:06:08",
        useful: 1238,
        funny: 642,
        cool: 815,
        elite: "2009,2010,2011,2012,2013,2014,2015,2016,2017",
        fans: 90,
        average_stars: 3.84,
        compliment_hot: 68,
        compliment_more: 22,
        compliment_profile: 8,
        compliment_cute: 9,
        compliment_list: 1,
        compliment_note: 29,
        compliment_plain: 49,
        compliment_cool: 108,
        compliment_funny: 108,
        compliment_writer: 128,
        compliment_photos: 13
    },
    {
        user_id: "r64WY53LOMRPowHDu2JIXw",
        name: "Karin",
        review_count: 1,
        yelping_since: "2016-03-13 19:42:37",
        useful: 0,
        funny: 0,
        cool: 0,
        elite: "",
        fans: 0,
        average_stars: 5.0,
        compliment_hot: 0,
        compliment_more: 0,
        compliment_profile: 0,
        compliment_cute: 0,
        compliment_list: 0,
        compliment_note: 0,
        compliment_plain: 0,
        compliment_cool: 1,
        compliment_funny: 0,
        compliment_writer: 0,
        compliment_photos: 0
    },
    {
        user_id: "Kgv4_8tmBIeZmVYu3rUhVg",
        name: "Bryan",
        review_count: 14,
        yelping_since: "2015-03-24 17:57:28",
        useful: 0,
        funny: 0,
        cool: 0,
        elite: "",
        fans: 0,
        average_stars: 5.0,
        compliment_hot: 0,
        compliment_more: 0,
        compliment_profile: 0,
        compliment_cute: 0,
        compliment_list: 0,
        compliment_note: 0,
        compliment_plain: 0,
        compliment_cool: 0,
        compliment_funny: 0,
        compliment_writer: 0,
        compliment_photos: 0
    },
    {
        user_id: "wyPkRQg3F5Yz2WqRFax7-g",
        name: "Jennifer",
        review_count: 1,
        yelping_since: "2015-10-25 01:34:38",
        useful: 0,
        funny: 2,
        cool: 0,
        elite: "",
        fans: 0,
        average_stars: 4.0,
        compliment_hot: 0,
        compliment_more: 0,
        compliment_profile: 0,
        compliment_cute: 0,
        compliment_list: 0,
        compliment_note: 0,
        compliment_plain: 1,
        compliment_cool: 0,
        compliment_funny: 0,
        compliment_writer: 0,
        compliment_photos: 0
    },
    {
        user_id: "jx-BchSqX2PlnMflR62Urw",
        name: "Jack",
        review_count: 188,
        yelping_since: "2012-02-27 03:50:40",
        useful: 275,
        funny: 175,
        cool: 118,
        elite: "",
        fans: 21,
        average_stars: 3.76,
        compliment_hot: 0,
        compliment_more: 3,
        compliment_profile: 0,
        compliment_cute: 0,
        compliment_list: 0,
        compliment_note: 10,
        compliment_plain: 6,
        compliment_cool: 1,
        compliment_funny: 1,
        compliment_writer: 5,
        compliment_photos: 0
    },
    {
        user_id: "LQbuEFUxqB0Ekt7Ps9ZnJA",
        name: "Shelby",
        review_count: 98,
        yelping_since: "2012-02-26 18:43:59",
        useful: 115,
        funny: 22,
        cool: 21,
        elite: "",
        fans: 1,
        average_stars: 3.88,
        compliment_hot: 1,
        compliment_more: 0,
        compliment_profile: 0,
        compliment_cute: 0,
        compliment_list: 0,
        compliment_note: 0,
        compliment_plain: 1,
        compliment_cool: 0,
        compliment_funny: 0,
        compliment_writer: 0,
        compliment_photos: 0
    },
    {
        user_id: "8aXyfFUFrypoE6PkUQBtmg",
        name: "Franz",
        review_count: 27,
        yelping_since: "2017-01-15 04:42:21",
        useful: 17,
        funny: 3,
        cool: 4,
        elite: "",
        fans: 1,
        average_stars: 4.37,
        compliment_hot: 1,
        compliment_more: 0,
        compliment_profile: 1,
        compliment_cute: 0,
        compliment_list: 0,
        compliment_note: 2,
        compliment_plain: 1,
        compliment_cool: 2,
        compliment_funny: 2,
        compliment_writer: 0,
        compliment_photos: 0
    },
    {
        user_id: "O_GWZZfQx7qv-n-CN7hsIA",
        name: "Omar",
        review_count: 9,
        yelping_since: "2012-07-08 06:21:47",
        useful: 22,
        funny: 3,
        cool: 3,
        elite: "",
        fans: 0,
        average_stars: 5.0,
        compliment_hot: 0,
        compliment_more: 0,
        compliment_profile: 0,
        compliment_cute: 0,
        compliment_list: 0,
        compliment_note: 1,
        compliment_plain: 0,
        compliment_cool: 1,
        compliment_funny: 1,
        compliment_writer: 0,
        compliment_photos: 0
    },
    {
        user_id: "lhPuskGXTRSjCwKOOOYeoA",
        name: "Victoria",
        review_count: 95,
        yelping_since: "2014-07-08 21:01:02",
        useful: 114,
        funny: 44,
        cool: 87,
        elite: "",
        fans: 3,
        average_stars: 4.32,
        compliment_hot: 5,
        compliment_more: 0,
        compliment_profile: 0,
        compliment_cute: 0,
        compliment_list: 0,
        compliment_note: 1,
        compliment_plain: 5,
        compliment_cool: 3,
        compliment_funny: 3,
        compliment_writer: 1,
        compliment_photos: 1
    },
    {
        user_id: "ZK6aHHTiNlQWCCmv69OXnA",
        name: "David",
        review_count: 60,
        yelping_since: "2010-12-18 01:51:08",
        useful: 101,
        funny: 71,
        cool: 41,
        elite: "",
        fans: 2,
        average_stars: 3.46,
        compliment_hot: 2,
        compliment_more: 1,
        compliment_profile: 0,
        compliment_cute: 0,
        compliment_list: 0,
        compliment_note: 2,
        compliment_plain: 4,
        compliment_cool: 4,
        compliment_funny: 4,
        compliment_writer: 1,
        compliment_photos: 0
    },
    {
        user_id: "0FMte0z-repSVWSJ_BaQTg",
        name: "Lindsay",
        review_count: 16,
        yelping_since: "2015-10-26 01:06:15",
        useful: 9,
        funny: 3,
        cool: 1,
        elite: "",
        fans: 2,
        average_stars: 4.44,
        compliment_hot: 0,
        compliment_more: 0,
        compliment_profile: 0,
        compliment_cute: 0,
        compliment_list: 0,
        compliment_note: 1,
        compliment_plain: 0,
        compliment_cool: 0,
        compliment_funny: 0,
        compliment_writer: 0,
        compliment_photos: 0
    },
    {
        user_id: "uu-gMsKDyKU_9MUItbNkHA",
        name: "Craig",
        review_count: 1209,
        yelping_since: "2008-01-18 16:25:21",
        useful: 4210,
        funny: 2831,
        cool: 2929,
        elite: "2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018",
        fans: 100,
        average_stars: 4.08,
        compliment_hot: 240,
        compliment_more: 26,
        compliment_profile: 53,
        compliment_cute: 24,
        compliment_list: 4,
        compliment_note: 173,
        compliment_plain: 300,
        compliment_cool: 412,
        compliment_funny: 412,
        compliment_writer: 161,
        compliment_photos: 82
    },
    {
        user_id: "CcJQAZfk6QkaBjPnKepLcg",
        name: "Deena",
        review_count: 69,
        yelping_since: "2008-07-28 10:36:00",
        useful: 112,
        funny: 42,
        cool: 41,
        elite: "",
        fans: 9,
        average_stars: 3.72,
        compliment_hot: 2,
        compliment_more: 2,
        compliment_profile: 0,
        compliment_cute: 1,
        compliment_list: 0,
        compliment_note: 3,
        compliment_plain: 2,
        compliment_cool: 2,
        compliment_funny: 2,
        compliment_writer: 1,
        compliment_photos: 1
    },
    {
        user_id: "C5pmvrZVeD9jEVWBiyIwzQ",
        name: "Sashah",
        review_count: 11,
        yelping_since: "2016-05-12 03:30:43",
        useful: 9,
        funny: 5,
        cool: 3,
        elite: "",
        fans: 1,
        average_stars: 1.62,
        compliment_hot: 0,
        compliment_more: 1,
        compliment_profile: 0,
        compliment_cute: 0,
        compliment_list: 0,
        compliment_note: 0,
        compliment_plain: 0,
        compliment_cool: 0,
        compliment_funny: 0,
        compliment_writer: 0,
        compliment_photos: 0
    },
    {
        user_id: "A7wZ9ajdlhbMeGIGAlUIbQ",
        name: "Kameran",
        review_count: 31,
        yelping_since: "2015-03-03 13:59:05",
        useful: 53,
        funny: 11,
        cool: 25,
        elite: "",
        fans: 2,
        average_stars: 3.81,
        compliment_hot: 1,
        compliment_more: 0,
        compliment_profile: 1,
        compliment_cute: 0,
        compliment_list: 0,
        compliment_note: 1,
        compliment_plain: 5,
        compliment_cool: 0,
        compliment_funny: 0,
        compliment_writer: 0,
        compliment_photos: 1
    },
    {
        user_id: "wud3mpvvW5yoSB_ZjS-Oig",
        name: "Allison",
        review_count: 112,
        yelping_since: "2010-09-12 15:25:14",
        useful: 132,
        funny: 57,
        cool: 61,
        elite: "",
        fans: 14,
        average_stars: 3.49,
        compliment_hot: 3,
        compliment_more: 1,
        compliment_profile: 0,
        compliment_cute: 4,
        compliment_list: 0,
        compliment_note: 4,
        compliment_plain: 4,
        compliment_cool: 3,
        compliment_funny: 3,
        compliment_writer: 2,
        compliment_photos: 4
    },
    {
        user_id: "e67TGUfNnz04A1Ahd0tF2A",
        name: "Swapnil",
        review_count: 44,
        yelping_since: "2013-08-22 02:55:51",
        useful: 43,
        funny: 21,
        cool: 6,
        elite: "",
        fans: 2,
        average_stars: 3.11,
        compliment_hot: 0,
        compliment_more: 0,
        compliment_profile: 0,
        compliment_cute: 0,
        compliment_list: 0,
        compliment_note: 0,
        compliment_plain: 0,
        compliment_cool: 0,
        compliment_funny: 0,
        compliment_writer: 1,
        compliment_photos: 0
    },
    {
        user_id: "4TCOItk-gIJROyNA5ftZ-Q",
        name: "Alma",
        review_count: 993,
        yelping_since: "2012-04-06 18:30:48",
        useful: 3482,
        funny: 1914,
        cool: 2024,
        elite: "2012,2013,2014,2015,2016,2017,2018",
        fans: 272,
        average_stars: 3.78,
        compliment_hot: 89,
        compliment_more: 27,
        compliment_profile: 9,
        compliment_cute: 7,
        compliment_list: 13,
        compliment_note: 119,
        compliment_plain: 296,
        compliment_cool: 223,
        compliment_funny: 223,
        compliment_writer: 86,
        compliment_photos: 91
    },
    {
        user_id: "bZURgbxLW7VHiqk45cafLA",
        name: "Karen",
        review_count: 22,
        yelping_since: "2012-03-26 18:15:06",
        useful: 29,
        funny: 19,
        cool: 12,
        elite: "",
        fans: 0,
        average_stars: 3.83,
        compliment_hot: 0,
        compliment_more: 0,
        compliment_profile: 0,
        compliment_cute: 0,
        compliment_list: 0,
        compliment_note: 1,
        compliment_plain: 1,
        compliment_cool: 0,
        compliment_funny: 0,
        compliment_writer: 0,
        compliment_photos: 0
    },
    {
        user_id: "t511fq0nFeppix5_MP-nxA",
        name: "Layal",
        review_count: 20,
        yelping_since: "2012-06-02 06:57:33",
        useful: 34,
        funny: 1,
        cool: 7,
        elite: "",
        fans: 2,
        average_stars: 4.75,
        compliment_hot: 0,
        compliment_more: 0,
        compliment_profile: 0,
        compliment_cute: 0,
        compliment_list: 0,
        compliment_note: 1,
        compliment_plain: 0,
        compliment_cool: 0,
        compliment_funny: 0,
        compliment_writer: 0,
        compliment_photos: 0
    },
    {
        user_id: "6CVEGPmmgCH4PDGUbeBpKw",
        name: "Jallil",
        review_count: 104,
        yelping_since: "2015-03-12 18:53:25",
        useful: 62,
        funny: 17,
        cool: 26,
        elite: "2017",
        fans: 9,
        average_stars: 4.27,
        compliment_hot: 4,
        compliment_more: 0,
        compliment_profile: 1,
        compliment_cute: 0,
        compliment_list: 0,
        compliment_note: 2,
        compliment_plain: 1,
        compliment_cool: 3,
        compliment_funny: 3,
        compliment_writer: 2,
        compliment_photos: 0
    },
    {
        user_id: "29yBaTFMSh-l6wNwy9d_mA",
        name: "Greg",
        review_count: 81,
        yelping_since: "2013-06-21 21:11:27",
        useful: 117,
        funny: 30,
        cool: 37,
        elite: "",
        fans: 7,
        average_stars: 3.92,
        compliment_hot: 0,
        compliment_more: 1,
        compliment_profile: 0,
        compliment_cute: 0,
        compliment_list: 0,
        compliment_note: 0,
        compliment_plain: 6,
        compliment_cool: 0,
        compliment_funny: 0,
        compliment_writer: 2,
        compliment_photos: 1
    },
    {
        user_id: "wQ0lKC5BMg3ZvCco8FI1EQ",
        name: "Stephanie",
        review_count: 1042,
        yelping_since: "2011-01-25 18:52:09",
        useful: 4807,
        funny: 2768,
        cool: 3147,
        elite: "2012,2013,2014,2015,2016,2017,2018",
        fans: 282,
        average_stars: 3.84,
        compliment_hot: 197,
        compliment_more: 20,
        compliment_profile: 19,
        compliment_cute: 12,
        compliment_list: 3,
        compliment_note: 139,
        compliment_plain: 249,
        compliment_cool: 246,
        compliment_funny: 246,
        compliment_writer: 179,
        compliment_photos: 183
    },
    {
        user_id: "ryf4jg4g3xweyIjkGOY3vg",
        name: "Haley",
        review_count: 443,
        yelping_since: "2008-09-13 05:27:51",
        useful: 975,
        funny: 383,
        cool: 601,
        elite: "2015,2016,2017,2018",
        fans: 63,
        average_stars: 4.21,
        compliment_hot: 6,
        compliment_more: 3,
        compliment_profile: 3,
        compliment_cute: 3,
        compliment_list: 0,
        compliment_note: 9,
        compliment_plain: 22,
        compliment_cool: 9,
        compliment_funny: 9,
        compliment_writer: 15,
        compliment_photos: 9
    },
    {
        user_id: "i7dva-DqwjyAtLVc2idhNA",
        name: "Pradeep",
        review_count: 63,
        yelping_since: "2012-07-26 15:13:56",
        useful: 110,
        funny: 55,
        cool: 72,
        elite: "2014,2015",
        fans: 8,
        average_stars: 4.19,
        compliment_hot: 14,
        compliment_more: 0,
        compliment_profile: 0,
        compliment_cute: 0,
        compliment_list: 0,
        compliment_note: 9,
        compliment_plain: 7,
        compliment_cool: 12,
        compliment_funny: 12,
        compliment_writer: 9,
        compliment_photos: 2
    },
    {
        user_id: "U4INQZOPSUaj8hMjLlZ3KA",
        name: "Michael",
        review_count: 4308,
        yelping_since: "2008-01-31 02:55:30",
        useful: 22757,
        funny: 10209,
        cool: 16249,
        elite: "2008,2010,2011,2012,2013,2014,2015",
        fans: 912,
        average_stars: 3.88,
        compliment_hot: 305,
        compliment_more: 75,
        compliment_profile: 43,
        compliment_cute: 13,
        compliment_list: 52,
        compliment_note: 442,
        compliment_plain: 656,
        compliment_cool: 801,
        compliment_funny: 801,
        compliment_writer: 663,
        compliment_photos: 634
    },
    {
        user_id: "W1AFbtC37Q1RzdrKS51NmQ",
        name: "Bobby",
        review_count: 376,
        yelping_since: "2010-03-10 23:55:33",
        useful: 1754,
        funny: 1036,
        cool: 1124,
        elite: "2013,2014,2015,2016,2017,2018",
        fans: 39,
        average_stars: 3.64,
        compliment_hot: 47,
        compliment_more: 6,
        compliment_profile: 2,
        compliment_cute: 2,
        compliment_list: 1,
        compliment_note: 38,
        compliment_plain: 77,
        compliment_cool: 106,
        compliment_funny: 106,
        compliment_writer: 52,
        compliment_photos: 3
    },
    {
        user_id: "-oHBgKNC6xGHIGdoZW3ReQ",
        name: "Chelsea",
        review_count: 55,
        yelping_since: "2008-09-06 02:56:01",
        useful: 161,
        funny: 120,
        cool: 61,
        elite: "2016,2017",
        fans: 7,
        average_stars: 3.81,
        compliment_hot: 3,
        compliment_more: 0,
        compliment_profile: 0,
        compliment_cute: 0,
        compliment_list: 0,
        compliment_note: 4,
        compliment_plain: 5,
        compliment_cool: 5,
        compliment_funny: 5,
        compliment_writer: 3,
        compliment_photos: 0
    },
    {
        user_id: "qvvpeBLkV4Shx0Teh87lPA",
        name: "Regina",
        review_count: 293,
        yelping_since: "2012-06-24 13:46:37",
        useful: 848,
        funny: 326,
        cool: 507,
        elite: "2014,2015,2016,2017,2018",
        fans: 30,
        average_stars: 3.95,
        compliment_hot: 31,
        compliment_more: 6,
        compliment_profile: 1,
        compliment_cute: 1,
        compliment_list: 2,
        compliment_note: 41,
        compliment_plain: 183,
        compliment_cool: 137,
        compliment_funny: 137,
        compliment_writer: 42,
        compliment_photos: 5
    },
    {
        user_id: "88lh7M1G24zM_ALekJ8mzQ",
        name: "Kamilah",
        review_count: 197,
        yelping_since: "2013-03-26 01:22:19",
        useful: 361,
        funny: 44,
        cool: 93,
        elite: "2013,2014,2015,2016,2017",
        fans: 15,
        average_stars: 4.02,
        compliment_hot: 8,
        compliment_more: 3,
        compliment_profile: 1,
        compliment_cute: 0,
        compliment_list: 1,
        compliment_note: 1,
        compliment_plain: 10,
        compliment_cool: 15,
        compliment_funny: 15,
        compliment_writer: 9,
        compliment_photos: 4
    },
    {
        user_id: "R_wlZO-jKFGEVJnSfWISqQ",
        name: "Madelene",
        review_count: 62,
        yelping_since: "2010-05-11 04:21:55",
        useful: 100,
        funny: 52,
        cool: 80,
        elite: "",
        fans: 6,
        average_stars: 3.92,
        compliment_hot: 0,
        compliment_more: 0,
        compliment_profile: 0,
        compliment_cute: 1,
        compliment_list: 0,
        compliment_note: 0,
        compliment_plain: 2,
        compliment_cool: 0,
        compliment_funny: 0,
        compliment_writer: 0,
        compliment_photos: 0
    },
    {
        user_id: "aoO6EXKupIDDDMMK4PG-iw",
        name: "Vivian",
        review_count: 20,
        yelping_since: "2012-11-07 18:54:40",
        useful: 32,
        funny: 16,
        cool: 11,
        elite: "",
        fans: 2,
        average_stars: 3.45,
        compliment_hot: 1,
        compliment_more: 0,
        compliment_profile: 0,
        compliment_cute: 0,
        compliment_list: 0,
        compliment_note: 1,
        compliment_plain: 3,
        compliment_cool: 2,
        compliment_funny: 2,
        compliment_writer: 3,
        compliment_photos: 0
    },
    {
        user_id: "on3cA28Qu-Eh50IuS2iq6w",
        name: "Priscilla",
        review_count: 16,
        yelping_since: "2013-07-25 02:48:09",
        useful: 34,
        funny: 5,
        cool: 4,
        elite: "",
        fans: 0,
        average_stars: 3.22,
        compliment_hot: 0,
        compliment_more: 0,
        compliment_profile: 0,
        compliment_cute: 0,
        compliment_list: 0,
        compliment_note: 0,
        compliment_plain: 0,
        compliment_cool: 0,
        compliment_funny: 0,
        compliment_writer: 0,
        compliment_photos: 0
    },
    {
        user_id: "XkLK2iBsgqF6mWwDfRgqqQ",
        name: "Seong",
        review_count: 1525,
        yelping_since: "2006-09-12 20:41:23",
        useful: 4012,
        funny: 2862,
        cool: 3573,
        elite: "2007,2008,2009,2010,2011,2012,2013,2014,2015,2016",
        fans: 124,
        average_stars: 3.75,
        compliment_hot: 1628,
        compliment_more: 75,
        compliment_profile: 56,
        compliment_cute: 207,
        compliment_list: 23,
        compliment_note: 557,
        compliment_plain: 497,
        compliment_cool: 1125,
        compliment_funny: 1125,
        compliment_writer: 139,
        compliment_photos: 43
    },
    {
        user_id: "we_ONmXR0wP5-Ejx9AbIAA",
        name: "Melissa",
        review_count: 56,
        yelping_since: "2010-08-03 19:24:28",
        useful: 65,
        funny: 6,
        cool: 14,
        elite: "",
        fans: 2,
        average_stars: 3.75,
        compliment_hot: 1,
        compliment_more: 1,
        compliment_profile: 0,
        compliment_cute: 2,
        compliment_list: 0,
        compliment_note: 0,
        compliment_plain: 3,
        compliment_cool: 2,
        compliment_funny: 2,
        compliment_writer: 2,
        compliment_photos: 2
    },
    {
        user_id: "SaWQOZm3N43fkJh82glIMQ",
        name: "Elizabeth",
        review_count: 259,
        yelping_since: "2011-10-05 21:38:54",
        useful: 801,
        funny: 544,
        cool: 363,
        elite: "2013",
        fans: 28,
        average_stars: 3.84,
        compliment_hot: 8,
        compliment_more: 4,
        compliment_profile: 5,
        compliment_cute: 0,
        compliment_list: 5,
        compliment_note: 9,
        compliment_plain: 17,
        compliment_cool: 24,
        compliment_funny: 24,
        compliment_writer: 28,
        compliment_photos: 0
    },
    {
        user_id: "akUC5qP68u0_frTwHLl61w",
        name: "Celine",
        review_count: 9,
        yelping_since: "2016-02-29 18:46:32",
        useful: 7,
        funny: 3,
        cool: 1,
        elite: "",
        fans: 0,
        average_stars: 2.78,
        compliment_hot: 0,
        compliment_more: 0,
        compliment_profile: 0,
        compliment_cute: 0,
        compliment_list: 0,
        compliment_note: 0,
        compliment_plain: 1,
        compliment_cool: 0,
        compliment_funny: 0,
        compliment_writer: 0,
        compliment_photos: 0
    },
    {
        user_id: "Ar3bat-NGasrXDiS7WF8OA",
        name: "Nette",
        review_count: 1090,
        yelping_since: "2010-02-22 17:55:36",
        useful: 7065,
        funny: 3807,
        cool: 5589,
        elite: "2010,2011,2012,2013,2014,2015,2016,2017,2018",
        fans: 426,
        average_stars: 3.8,
        compliment_hot: 605,
        compliment_more: 31,
        compliment_profile: 43,
        compliment_cute: 55,
        compliment_list: 11,
        compliment_note: 276,
        compliment_plain: 366,
        compliment_cool: 564,
        compliment_funny: 564,
        compliment_writer: 228,
        compliment_photos: 178
    },
    {
        user_id: "LRWg8McG8i9iCY4SOmpa-Q",
        name: "David",
        review_count: 3,
        yelping_since: "2013-05-31 18:14:19",
        useful: 16,
        funny: 0,
        cool: 0,
        elite: "",
        fans: 0,
        average_stars: 1.0,
        compliment_hot: 0,
        compliment_more: 0,
        compliment_profile: 0,
        compliment_cute: 0,
        compliment_list: 0,
        compliment_note: 0,
        compliment_plain: 0,
        compliment_cool: 0,
        compliment_funny: 0,
        compliment_writer: 0,
        compliment_photos: 0
    },
    {
        user_id: "xceJT1G2Yhel3W2lRxRTDA",
        name: "Gregory Paul",
        review_count: 40,
        yelping_since: "2008-12-25 20:18:40",
        useful: 58,
        funny: 21,
        cool: 14,
        elite: "",
        fans: 0,
        average_stars: 3.31,
        compliment_hot: 0,
        compliment_more: 0,
        compliment_profile: 0,
        compliment_cute: 0,
        compliment_list: 0,
        compliment_note: 0,
        compliment_plain: 6,
        compliment_cool: 2,
        compliment_funny: 2,
        compliment_writer: 0,
        compliment_photos: 0
    },
    {
        user_id: "fmPko8NeSgKpb5YwhLJ_gg",
        name: "Shannon",
        review_count: 249,
        yelping_since: "2009-12-23 05:53:31",
        useful: 212,
        funny: 72,
        cool: 101,
        elite: "",
        fans: 15,
        average_stars: 3.06,
        compliment_hot: 7,
        compliment_more: 1,
        compliment_profile: 0,
        compliment_cute: 2,
        compliment_list: 0,
        compliment_note: 25,
        compliment_plain: 40,
        compliment_cool: 20,
        compliment_funny: 20,
        compliment_writer: 7,
        compliment_photos: 5
    },
    {
        user_id: "syA7uYoDjohc7gWBWaEZmw",
        name: "Stephanie",
        review_count: 90,
        yelping_since: "2008-08-04 02:27:06",
        useful: 304,
        funny: 102,
        cool: 180,
        elite: "2008,2009,2010",
        fans: 7,
        average_stars: 4.1,
        compliment_hot: 23,
        compliment_more: 2,
        compliment_profile: 0,
        compliment_cute: 1,
        compliment_list: 5,
        compliment_note: 11,
        compliment_plain: 17,
        compliment_cool: 31,
        compliment_funny: 31,
        compliment_writer: 7,
        compliment_photos: 1
    },
    {
        user_id: "E0TsnBuNAOSnXKiLe18l1A",
        name: "Rachael",
        review_count: 173,
        yelping_since: "2013-05-22 02:29:38",
        useful: 204,
        funny: 58,
        cool: 90,
        elite: "2015,2016,2017,2018",
        fans: 11,
        average_stars: 4.51,
        compliment_hot: 1,
        compliment_more: 0,
        compliment_profile: 0,
        compliment_cute: 1,
        compliment_list: 0,
        compliment_note: 1,
        compliment_plain: 6,
        compliment_cool: 3,
        compliment_funny: 3,
        compliment_writer: 2,
        compliment_photos: 2
    },
    {
        user_id: "SNQcE_Bc0QAbxFu5F1dTzw",
        name: "Michele",
        review_count: 244,
        yelping_since: "2011-02-01 01:29:47",
        useful: 435,
        funny: 76,
        cool: 145,
        elite: "",
        fans: 23,
        average_stars: 4.38,
        compliment_hot: 6,
        compliment_more: 5,
        compliment_profile: 0,
        compliment_cute: 1,
        compliment_list: 0,
        compliment_note: 4,
        compliment_plain: 13,
        compliment_cool: 13,
        compliment_funny: 13,
        compliment_writer: 9,
        compliment_photos: 6
    },
    {
        user_id: "KRAGCgnAC0Lmw9YaVSqY7w",
        name: "Kristen",
        review_count: 9,
        yelping_since: "2015-04-25 18:18:38",
        useful: 21,
        funny: 3,
        cool: 3,
        elite: "",
        fans: 1,
        average_stars: 4.0,
        compliment_hot: 0,
        compliment_more: 0,
        compliment_profile: 0,
        compliment_cute: 0,
        compliment_list: 0,
        compliment_note: 0,
        compliment_plain: 0,
        compliment_cool: 0,
        compliment_funny: 0,
        compliment_writer: 0,
        compliment_photos: 0
    },
    {
        user_id: "Fw4UjJ6yBeyPB27Y4wwEUQ",
        name: "Alfred",
        review_count: 21,
        yelping_since: "2008-11-06 14:35:38",
        useful: 94,
        funny: 26,
        cool: 70,
        elite: "",
        fans: 23,
        average_stars: 4.16,
        compliment_hot: 70,
        compliment_more: 7,
        compliment_profile: 0,
        compliment_cute: 0,
        compliment_list: 0,
        compliment_note: 76,
        compliment_plain: 103,
        compliment_cool: 107,
        compliment_funny: 107,
        compliment_writer: 4,
        compliment_photos: 33
    },
    {
        user_id: "jVvKhFgCTW0PgkMbiCkp3A",
        name: "Jerron",
        review_count: 37,
        yelping_since: "2011-04-18 01:34:29",
        useful: 35,
        funny: 11,
        cool: 10,
        elite: "",
        fans: 1,
        average_stars: 4.14,
        compliment_hot: 1,
        compliment_more: 0,
        compliment_profile: 0,
        compliment_cute: 0,
        compliment_list: 0,
        compliment_note: 0,
        compliment_plain: 2,
        compliment_cool: 4,
        compliment_funny: 4,
        compliment_writer: 0,
        compliment_photos: 0
    },
    {
        user_id: "4i4lyXBigT2HShIjw7TbDw",
        name: "Kurt",
        review_count: 244,
        yelping_since: "2007-07-25 01:08:12",
        useful: 124,
        funny: 30,
        cool: 84,
        elite: "2009,2010,2011",
        fans: 6,
        average_stars: 3.81,
        compliment_hot: 1,
        compliment_more: 0,
        compliment_profile: 0,
        compliment_cute: 2,
        compliment_list: 1,
        compliment_note: 5,
        compliment_plain: 1,
        compliment_cool: 2,
        compliment_funny: 2,
        compliment_writer: 1,
        compliment_photos: 1
    },
];
const yelpUserTip = [
    {
        user_id: "UPw5DWs_b-e2JRBS-t37Ag",
        business_id: "VaKXUpmWTTWDKbpJ3aQdMw",
        text: "Great for watching games, ufc, and whatever else tickles yer fancy",
        date: "2014-16-27 03:51:24",
        compliment_count: 0
    },
    {
        user_id: "Ocha4kZBHb4JK0lOWvE0sg",
        business_id: "OPiPeoJiv92rENwbq76orA",
        text: "Happy Hour 2-4 daily with 1\/2 price drinks and slushes AND after 8 half price shakes.  They actually have a peanut butter and bacon shake.",
        date: "2013-15-25 06:00:56",
        compliment_count: 8
    },
    {
        user_id: "jRyO2V1pA4CdVVqCIOPc1Q",
        business_id: "5KheTjYPu1HcQzQFtm4_vw",
        text: "Good chips and salsa. Loud at times. Good service. Bathrooms AWFUL. So that tanks my view on this place.",
        date: "2011-17-26 01:46:17",
        compliment_count: 2428
    },
    {
        user_id: "FuTJWFYm4UKqewaosss1KA",
        business_id: "TkoyGi8J7YFjA6SbaRzrxg",
        text: "The setting and decoration here is amazing. Come check out the waterfall fountain in the middle!",
        date: "2014-16-23 21:32:49",
        compliment_count: 60
    },
    {
        user_id: "LUlKtaM3nXd-E4N4uOk_fQ",
        business_id: "AkL6Ous6A1atZejfZXn1Bg",
        text: "Molly is definately taking a picture with Santa lols",
        date: "2012-13-06 00:19:27",
        compliment_count: 33
    },
    {
        user_id: "iAd8XaHxv05iXyEiZ62Ibw",
        business_id: "kj1p6NwUGROOoqNySf0I1Q",
        text: "It's true! The drunken noodles are outrageous!",
        date: "2011-16-31 18:02:42",
        compliment_count: 1
    },
    {
        user_id: "w8p4JW6-ERsbg8aB5wjEAg",
        business_id: "0hudPyuCBlKg79OwKBw-eQ",
        text: "Only worth a visit in the summer time, to take advantage of the huge sun soaked patio.",
        date: "2012-16-11 23:06:21",
        compliment_count: 14
    },
    {
        user_id: "iPJAN6rJHv92WE2h9b3lAA",
        business_id: "r49iBfbnfoK7yt4rdsL_7g",
        text: "Hands down best AYCE in town! Love it!",
        date: "2016-15-05 06:39:33",
        compliment_count: 5
    },
    {
        user_id: "VLy6l8L72adD7iTBNqiPXw",
        business_id: "YCRCFBr6myPS49on2aS2pQ",
        text: "Sat in the drive thru this afternoon for 30 minutes and then was handed the wrong coffee. Booooo, I'm seriously here every day and this was the first bad experience",
        date: "2017-14-13 03:29:40",
        compliment_count: 0
    },
    {
        user_id: "CXi7I5J-ItLGJNyKPkI5gA",
        business_id: "RTBIiq-fJUXRsrzbL4MCqw",
        text: "Okay so I had a groupon for a nearby service center, but their wait time was 3 hours! Once again, I find myself back at this Brake Masters. Idk why I bother with anywhere else; This place is great!",
        date: "2013-14-08 20:55:15",
        compliment_count: 11
    },
    {
        user_id: "8zXgNCkusOHMwh5Tj_8yCQ",
        business_id: "qrSsS0pk7SL67MP5nN8tlg",
        text: "More parking in the back of the restaurant",
        date: "2013-16-22 05:10:12",
        compliment_count: 0
    },
    {
        user_id: "hQ98T_hy1CoSWw55zA49VQ",
        business_id: "oGASRzKGpuiP12ilQH_nKg",
        text: "Best pretzels this side of the Rhein. Wash down with the Franziskaner Weissbier.",
        date: "2010-16-04 15:41:16",
        compliment_count: 0
    },
    {
        user_id: "pU6GoRTcl1rIOi6zMynjog",
        business_id: "63bHLJUomC22Xdm3IjgBtw",
        text: "Having the yellow curry, summer rolls and a coke. I would recommend the rolls but the curry was incredible!",
        date: "2011-13-18 18:29:05",
        compliment_count: 272
    },
    {
        user_id: "oIHhfloe5VQamDFDB2dr1Q",
        business_id: "wZhB4U003eg2GQ-F7D2D4A",
        text: "When you receive the bag of seafood tie it up and then mix it up that way all the flavours get into the seafood. As well for the owner play less Drake music please and thank you when I'm here. :D Congrats Guys",
        date: "2016-18-12 22:18:07",
        compliment_count: 16
    },
    {
        user_id: "NEN5RFpZp7DE6K1PK2KZzg",
        business_id: "Cni2l-VKG_pdospJ6xliXQ",
        text: "2nd stop for the pub-crawl! Yay!",
        date: "2011-15-09 03:43:39",
        compliment_count: 0
    },
    {
        user_id: "Fzz-0v1yHLaWuTV64b1miA",
        business_id: "EZZjaiV8ik05NUepqdeP2A",
        text: "Really delicious food and amazing service.",
        date: "2018-14-14 21:35:49",
        compliment_count: 1
    },
    {
        user_id: "CbmNBkKa9QKNxPiN_whFUw",
        business_id: "xZfPdAYeimiruXuGR4nSUA",
        text: "Dinner!!",
        date: "2011-14-21 22:43:28",
        compliment_count: 4
    },
    {
        user_id: "3KkT6SmPFLGvBS1pnDBr8g",
        business_id: "D2nfOrnJ2OBlX_428sKyMg",
        text: "Long lines at lunch!!",
        date: "2011-15-30 17:10:16",
        compliment_count: 705
    },
    {
        user_id: "kMcz3zQgNjZYV65qY9ztGA",
        business_id: "C7JaaErXLB3B3486LfWg5w",
        text: "Go somewhere else to buy a car or mini van.\nRude, assuming sales staff; they are not going to lower the price on a vehicle,  The black sales guy is unprofessional and barely knows his job; he is rude and insults customers.",
        date: "2013-15-17 06:22:49",
        compliment_count: 133
    },
    {
        user_id: "JnHaPHkRO2_8V-DysmIBVw",
        business_id: "j9I2YkFCOKyAEb_3FbFqUA",
        text: "#poutinecrawl #yyc stop #1",
        date: "2011-14-09 18:58:36",
        compliment_count: 35
    },
    {
        user_id: "EZbvMdvCA2D9vF6VjILYXA",
        business_id: "LrO_Xy6lfpbTgFoJcOjY4w",
        text: "I love the gourmet veggie pizza!!",
        date: "2015-15-21 01:13:24",
        compliment_count: 0
    },
    {
        user_id: "pDAqvfflIM4AM23VRpqAaw",
        business_id: "0PVxodALQu-soL5J8bjerQ",
        text: "If there's a more authentic breakfast place in Pittsburgh, I haven't found it. Ritter's is comfort food at its best!",
        date: "2012-17-24 16:24:09",
        compliment_count: 7
    },
    {
        user_id: "gGlFgp4nXNL5azpUtLK05w",
        business_id: "cnfYugAYBFKgwDCTAVdViA",
        text: "No",
        date: "2015-15-29 04:25:09",
        compliment_count: 111
    },
    {
        user_id: "HmILc-lgVKZS7mWNdYCSJw",
        business_id: "1l7gJx3BVWBZ8Wx1vPCkeA",
        text: "New Dr Who! He talks with an accent, \" I'm the Doctor\" Oui Garcon!",
        date: "2013-14-30 04:03:27",
        compliment_count: 98
    },
    {
        user_id: "lesnCKZUYH554j-EDZBlTw",
        business_id: "7sPNbCx7vGAaH7SbNPZ6oA",
        text: "Late night burger cravings...",
        date: "2012-18-02 06:25:54",
        compliment_count: 1
    },
    {
        user_id: "alUuOskFSl1bODjnce2PpQ",
        business_id: "PEb1Hm0kQ52cObjPAE6nFQ",
        text: "Cash only! ATM on site",
        date: "2014-19-06 23:29:08",
        compliment_count: 4056
    },
    {
        user_id: "hf27xTME3EiCp6NL6VtWZQ",
        business_id: "i6G3zsEJIqpGktMWyffXjw",
        text: "Holiday party",
        date: "2013-18-19 21:29:53",
        compliment_count: 37
    },
    {
        user_id: "TYCkjEHPSJSnFb6m6GDluw",
        business_id: "XP0YZRa6Un25QaOH2g1ivA",
        text: "oh damn. run do not walk to circle-h. pulled pork.",
        date: "2011-16-30 22:00:46",
        compliment_count: 543
    },
    {
        user_id: "r64WY53LOMRPowHDu2JIXw",
        business_id: "p-8AMN9Q0qwym-3Pdle20Q",
        text: "Good mix of cuisine",
        date: "2017-18-10 19:32:16",
        compliment_count: 1
    },
    {
        user_id: "r5ggPC6OccLk6dDl5yqsJQ",
        business_id: "wyPkRQg3F5Yz2WqRFax7-g",
        text: "Burgers, salads, entrees of chili and even a ribeye steak.",
        date: "2010-17-18 02:00:22",
        compliment_count: 1
    },
    {
        user_id: "8aXyfFUFrypoE6PkUQBtmg",
        business_id: "PtwW1Hwme8Y0wy54zNr8Xw",
        text: "Wonderful food and great service! I will definitely be back with my family!",
        date: "2014-16-07 17:04:01",
        compliment_count: 9
    },
    {
        user_id: "O_GWZZfQx7qv-n-CN7hsIA",
        business_id: "IzC1oXHT_TxYej_6YTfBnA",
        text: "Over 100 group fitness class a week!!!",
        date: "2012-16-16 18:25:20",
        compliment_count: 3
    },
    {
        user_id: "lhPuskGXTRSjCwKOOOYeoA",
        business_id: "e5Qw3r7mkwPLcdDzZzTeew",
        text: "good stuff!",
        date: "2011-17-12 20:41:17",
        compliment_count: 19
    },
    {
        user_id: "ZXIOnRHvDUK-corzrUbqoA",
        business_id: "7jKDOB9b_nijq0-djwyUTw",
        text: "Tara did a great job. I will go back for another hair cut.",
        date: "2016-05-22 00:11:14",
        compliment_count: 0
    },
    {
        user_id: "2EuPAGalYnP7eSxPgFCNDg",
        business_id: "NqCHqgF_FY0Aw9gD-Z3ABQ",
        text: "Its open! Lobby closes at 10pm.The drive-thru open till 11pm",
        date: "2014-06-03 04:23:22",
        compliment_count: 1
    },
    {
        user_id: "ZK6aHHTiNlQWCCmv69OXnA",
        business_id: "DkYS3arLOhA8si5uUEmHOw",
        text: "You know I had to come back first thing after checking into the hotel!! :]",
        date: "2012-11-04 03:58:17",
        compliment_count: 18
    },
    {
        user_id: "0FMte0z-repSVWSJ_BaQTg",
        business_id: "6pSwIh7gbTEpfxDlKEiB5A",
        text: "PTL time!",
        date: "2012-05-25 00:05:01",
        compliment_count: 1
    },
    {
        user_id: "uu-gMsKDyKU_9MUItbNkHA",
        business_id: "I0f12eU-xFn6Kd_4H57jrQ",
        text: "Soup was awesome!!",
        date: "2016-17-30 08:08:12",
        compliment_count: 1475
    },
    {
        user_id: "CcJQAZfk6QkaBjPnKepLcg",
        business_id: "vYn0gishV27DpfM_loZITQ",
        text: "Southwestern egg rolls...yummy!",
        date: "2013-15-11 17:45:51",
        compliment_count: 16
    },
    {
        user_id: "ge72-Ti-WqR3w0YENY5pRQ",
        business_id: "Lzv68iVkRHstVvW3aXNWkA",
        text: "So far everything has been great",
        date: "2015-19-28 00:55:47",
        compliment_count: 0
    },
    {
        user_id: "gtwM4ijo65AN4DvXdgCu_w",
        business_id: "19umlhmVB9O3njIBfRAe8g",
        text: "Hey mom look at me! I'm Nancy friggen' Kerrigan!!",
        date: "2014-18-24 03:56:50",
        compliment_count: 1
    },
    {
        user_id: "t511fq0nFeppix5_MP-nxA",
        business_id: "ZhLSAiRj9kANxf8m2SBfRA",
        text: "New Milk Tea Recipe! not as sweet, and nice tea flavor.",
        date: "2017-13-21 22:30:13",
        compliment_count: 1
    },
    {
        user_id: "29yBaTFMSh-l6wNwy9d_mA",
        business_id: "jaJnPIX9VxsFyfV5zQwk0g",
        text: "Lots of people on the second floor!",
        date: "2011-15-01 23:54:04",
        compliment_count: 10
    },
    {
        user_id: "qvvpeBLkV4Shx0Teh87lPA",
        business_id: "XXGzCIcxzAZ6H98mxZbdqA",
        text: "Um. All kinds of awesome!  Big clean and all the Chinese and western groceries you can imagine.",
        date: "2010-14-26 15:34:54",
        compliment_count: 0
    },
    {
        user_id: "R_wlZO-jKFGEVJnSfWISqQ",
        business_id: "Z15a7_8FQ82_baSJiqMoIw",
        text: "Tons of wing flavors...",
        date: "2012-18-03 21:54:49",
        compliment_count: 0
    },
    {
        user_id: "aoO6EXKupIDDDMMK4PG-iw",
        business_id: "e7207sqC-pSn6GIf31ikhQ",
        text: "Birthday breakfast!",
        date: "2013-15-21 13:29:23",
        compliment_count: 0
    },
    {
        user_id: "we_ONmXR0wP5-Ejx9AbIAA",
        business_id: "JTl1nXrukJTScI0Uz0x2Fg",
        text: "Try the green gables IPA, it is delicious!!",
        date: "2016-14-18 20:23:00",
        compliment_count: 0
    },
    {
        user_id: "akUC5qP68u0_frTwHLl61w",
        business_id: "IBxD5xo8o3FDquF1dkA31g",
        text: "Save room for a yummy scone!",
        date: "2013-14-19 20:45:57",
        compliment_count: 0
    },
    {
        user_id: "syA7uYoDjohc7gWBWaEZmw",
        business_id: "V3U21fM0in_0qpKUMYPNOw",
        text: "15 dollar credit card minimum, no AMEX",
        date: "2012-13-19 01:47:32",
        compliment_count: 0
    },
    {
        user_id: "xceJT1G2Yhel3W2lRxRTDA",
        business_id: "enzgrlkltK3PO-KGg1pkSQ",
        text: "Mani\/Pedi for $15.",
        date: "2012-17-27 19:27:17",
        compliment_count: 0
    }
]
module.exports = { yelpUser, yelpUserTip };
